name: Maestro E2E Web Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run Tests on Maestro Cloud
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
        run: |
          maestro cloud --api-key "$MAESTRO_API_KEY" --flows . --name "First Maestro Project" --format HTML --output maestro-cloud-report.html